import { Patient, Appointment, Recall, RecallStatus, Conversation, MessageSender, MissedCall, MessageType, Product, Bundle, BXGYRule, UpsellRule, PaymentPlan, ScaledOffer, DownsellRule, UpgradeCredit, MembershipPlan, MemberSubscription, MembershipEvent, CampaignTriggerConfig, CampaignMessage, CustomerCommunicationPreferences, CampaignQueueItem, CampaignMetrics } from './types';

export const mockPatients: Patient[] = [
  { id: 1, name: 'Amelia Johnson', phone: '+44 7700 900001', email: 'amelia.j@example.com', lastVisit: '2023-10-15', nextDue: '2024-10-15' },
  { id: 2, name: 'Benjamin Carter', phone: '+44 7700 900002', email: 'b.carter@example.com', lastVisit: '2024-04-20', nextDue: '2024-07-20' },
  { id: 3, name: 'Chloe Davies', phone: '+44 7700 900003', email: 'chloe.d@example.com', lastVisit: '2024-01-10', nextDue: '2025-01-10' },
  { id: 4, name: 'Daniel Smith', phone: '+44 7700 900004', email: 'dan.smith@example.com', lastVisit: '2024-06-01', nextDue: '2024-09-01' },
  { id: 5, name: 'Sophia Miller', phone: '+44 7700 900005', email: 'sophia.m@example.com', lastVisit: '2024-07-10', nextDue: '2025-01-10' },
  { id: 6, name: 'Jacob Moore', phone: '+44 7700 900006', email: 'jacob.m@example.com', lastVisit: '2024-07-12', nextDue: '2024-10-12' },
];

export const mockUpcomingAppointments: Appointment[] = [
  { id: 1, patientName: 'Olivia Williams', time: '09:00 AM', type: 'Prenatal Scan (20wk)', status: 'Confirmed', reviewStatus: 'Pending', price: 220 },
  { id: 2, patientName: 'George Brown', time: '09:30 AM', type: 'Abdominal Ultrasound', status: 'Confirmed', reviewStatus: 'Pending', price: 150 },
  { id: 3, patientName: 'Isla Taylor', time: '10:00 AM', type: 'Follow-up Scan', status: 'Pending', reviewStatus: 'Pending', price: 90 },
  { id: 4, patientName: 'Harry Wilson', time: '11:00 AM', type: 'Musculoskeletal Scan', status: 'Confirmed', reviewStatus: 'Pending', price: 180 },
];

export const mockRecentAppointments: Appointment[] = [
    { id: 5, patientName: 'Amelia Johnson', time: 'Yesterday', type: 'Annual Check-up', status: 'Completed', reviewStatus: 'Pending', price: 250 },
    { id: 6, patientName: 'Sophia Miller', time: 'Yesterday', type: 'Prenatal Scan (12wk)', status: 'Completed', reviewStatus: 'Requested', price: 120 },
    { id: 7, patientName: 'Jacob Moore', time: '2 days ago', type: 'Abdominal Scan', status: 'Completed', reviewStatus: 'Completed', price: 150 },
];

export const mockRecalls: Recall[] = [
  { id: 1, patient: mockPatients[0], status: RecallStatus.Due },
  { id: 2, patient: mockPatients[1], status: RecallStatus.Contacted },
  { id: 3, patient: mockPatients[2], status: RecallStatus.Booked },
  { id: 4, patient: mockPatients[3], status: RecallStatus.Due },
];

export const mockConversations: Conversation[] = [
  {
    id: 1,
    patientName: 'Benjamin Carter',
    lastMessage: 'Great, see you then!',
    timestamp: '10:32 AM',
    unread: false,
    messages: [
      { id: 1, sender: MessageSender.System, type: MessageType.Standard, text: 'Hi Benjamin, this is SonoClinic. We noticed you are due for your follow-up scan. Please let us know when you would like to book.', timestamp: 'Yesterday 09:00 AM' },
      { id: 2, sender: MessageSender.Patient, type: MessageType.Standard, text: 'Hi, can I book for next Tuesday morning?', timestamp: 'Yesterday 09:05 AM' },
      { id: 3, sender: MessageSender.Clinic, type: MessageType.Standard, text: 'Certainly, we have an opening at 9:30 AM on Tuesday. Does that work for you?', timestamp: 'Yesterday 09:10 AM' },
      { id: 4, sender: MessageSender.Patient, type: MessageType.Standard, text: 'Perfect, please book me in.', timestamp: '10:30 AM' },
      { id: 5, sender: MessageSender.Clinic, type: MessageType.Standard, text: 'You are all set. We have sent a confirmation to your email. Great, see you then!', timestamp: '10:32 AM' },
    ],
  },
  {
    id: 2,
    patientName: 'Isla Taylor',
    lastMessage: 'Can I reschedule for Friday?',
    timestamp: '02:15 PM',
    unread: true,
    messages: [
      { id: 1, sender: MessageSender.System, type: MessageType.Standard, text: 'Reminder: Your appointment is tomorrow at 10:00 AM.', timestamp: '11:00 AM' },
      { id: 2, sender: MessageSender.Patient, type: MessageType.Standard, text: 'Hi, something came up. Can I reschedule for Friday?', timestamp: '02:15 PM' },
    ],
  },
    {
    id: 3,
    patientName: 'Sophia Miller',
    lastMessage: 'Thank you for your feedback request.',
    timestamp: 'Yesterday',
    unread: false,
    messages: [
        { id: 1, sender: MessageSender.System, type: MessageType.FeedbackRequest, text: 'Hi Sophia, thank you for visiting SonoClinic today! We\'d love to hear about your experience. Please share your feedback here.', payload: { appointmentId: 6 }, timestamp: 'Yesterday 03:00 PM' },
    ]
  }
];

export const mockMissedCalls: MissedCall[] = [
    { id: 1, callerNumber: '+44 7700 900111', timestamp: '2 hours ago', status: 'Pending' }
];

export const analyticsData = {
  noShowRate: [
    { name: 'Jan', rate: 12 }, { name: 'Feb', rate: 11 }, { name: 'Mar', rate: 9 },
    { name: 'Apr', rate: 7 }, { name: 'May', rate: 6 }, { name: 'Jun', rate: 5 },
  ],
  recallEffectiveness: [
    { name: 'Sent', value: 250 },
    { name: 'Booked', value: 180 },
  ],
  reviewRatings: [
    { name: '5 Stars', value: 85 }, { name: '4 Stars', value: 25 },
    { name: '3 Stars', value: 5 }, { name: '1-2 Stars', value: 2 },
  ],
};

export const mockProducts: Product[] = [
  {
    id: 1,
    name: 'Printed Scan Photos (4x6)',
    description: 'High-quality printed ultrasound images',
    price: 5,
    category: 'Prints',
    stockLevel: 50,
    reorderPoint: 20,
    active: true,
    trackStock: true,
  },
  {
    id: 2,
    name: 'Digital Scan Package',
    description: 'Digital copies of all scan images delivered via email',
    price: 15,
    category: 'Digital',
    stockLevel: 0,
    reorderPoint: 0,
    active: true,
    trackStock: false,
  },
  {
    id: 3,
    name: 'Premium Photo Frame',
    description: 'Elegant frame for your baby scan photos',
    price: 25,
    category: 'Keepsakes',
    stockLevel: 15,
    reorderPoint: 5,
    active: true,
    trackStock: true,
  },
  {
    id: 4,
    name: 'USB Drive with Scans',
    description: '16GB USB drive preloaded with your scan images and videos',
    price: 20,
    category: 'Digital',
    stockLevel: 30,
    reorderPoint: 10,
    active: true,
    trackStock: true,
  },
  {
    id: 5,
    name: 'Baby Heartbeat Recording',
    description: 'Audio recording of your baby\'s heartbeat',
    price: 10,
    category: 'Keepsakes',
    stockLevel: 0,
    reorderPoint: 0,
    active: true,
    trackStock: false,
  },
  {
    id: 6,
    name: 'Scan Video Recording',
    description: 'Full video recording of your ultrasound session',
    price: 35,
    category: 'Video',
    stockLevel: 0,
    reorderPoint: 0,
    active: true,
    trackStock: false,
  },
  {
    id: 7,
    name: 'Gender Reveal Package',
    description: 'Sealed envelope with gender reveal photo',
    price: 12,
    category: 'Keepsakes',
    stockLevel: 25,
    reorderPoint: 10,
    active: true,
    trackStock: true,
  },
  {
    id: 8,
    name: 'Legacy Product (Discontinued)',
    description: 'Old product no longer available',
    price: 50,
    category: 'Other',
    stockLevel: 0,
    reorderPoint: 0,
    active: false,
    trackStock: false,
  },
];

export const mockBundles: Bundle[] = [
  {
    id: 1,
    name: 'Complete Prenatal Package',
    description: 'Includes 12-week scan, 20-week scan, digital photos, and printed keepsake',
    items: [
      { type: 'service', id: 2, name: 'Prenatal Scan (12wk)', quantity: 1 },
      { type: 'service', id: 1, name: 'Prenatal Scan (20wk)', quantity: 1 },
      { type: 'product', id: 2, name: 'Digital Scan Package', quantity: 1 },
      { type: 'product', id: 1, name: 'Printed Scan Photos (4x6)', quantity: 1 },
    ],
    discountType: 'percentage',
    discountValue: 15, // 15% off
    active: true,
    category: 'Prenatal',
  },
  {
    id: 2,
    name: 'Memory Bundle',
    description: 'Premium frame, printed photos, and USB drive with all your scan images',
    items: [
      { type: 'product', id: 3, name: 'Premium Photo Frame', quantity: 1 },
      { type: 'product', id: 1, name: 'Printed Scan Photos (4x6)', quantity: 2 },
      { type: 'product', id: 4, name: 'USB Drive with Scans', quantity: 1 },
    ],
    discountType: 'fixed',
    discountValue: 10, // £10 off
    active: true,
    category: 'Keepsakes',
  },
  {
    id: 3,
    name: 'Digital Premium Package',
    description: 'All digital content: scan package, video recording, and heartbeat audio',
    items: [
      { type: 'product', id: 2, name: 'Digital Scan Package', quantity: 1 },
      { type: 'product', id: 6, name: 'Scan Video Recording', quantity: 1 },
      { type: 'product', id: 5, name: 'Baby Heartbeat Recording', quantity: 1 },
    ],
    discountType: 'percentage',
    discountValue: 20, // 20% off
    active: true,
    category: 'Digital',
  },
  {
    id: 4,
    name: 'Family Scan Special',
    description: 'Two scans plus gender reveal package',
    items: [
      { type: 'service', id: 1, name: 'Follow-up Scan', quantity: 2 },
      { type: 'product', id: 7, name: 'Gender Reveal Package', quantity: 1 },
    ],
    discountType: 'fixed',
    discountValue: 25,
    finalPrice: 175, // Override: normally would be £205, special price £175
    active: true,
    category: 'Special Offers',
  },
  {
    id: 5,
    name: 'Inactive Bundle Example',
    description: 'This bundle is not active',
    items: [
      { type: 'product', id: 1, name: 'Printed Scan Photos (4x6)', quantity: 1 },
    ],
    discountType: 'percentage',
    discountValue: 10,
    active: false,
  },
];

export const mockBXGYRules: BXGYRule[] = [
  {
    id: 1,
    name: 'Buy 3 Photo Products, Get 1 Free',
    description: 'Add any 3 photo products to your cart and get the cheapest one free',
    active: true,
    buyQuantity: 3,
    buyItemType: 'product',
    buyCategory: 'Prints',
    ruleType: 'free_item',
    getQuantity: 1,
    targetType: 'category',
    getCategory: 'Prints',
  },
  {
    id: 2,
    name: 'Buy 2 Scans, Get 20% Off 3rd',
    description: 'Book 3 scans and get 20% off the cheapest one',
    active: true,
    buyQuantity: 2,
    buyItemType: 'service',
    ruleType: 'percentage_discount',
    getQuantity: 1,
    discountValue: 20,
    targetType: 'same_item',
  },
  {
    id: 3,
    name: 'Buy Frame, Get 50% Off USB Drive',
    description: 'Purchase a premium photo frame and get 50% off a USB drive',
    active: true,
    buyQuantity: 1,
    buyItemType: 'product',
    buyItemId: 3, // Premium Photo Frame
    ruleType: 'percentage_discount',
    getQuantity: 1,
    getItemType: 'product',
    getItemId: 4, // USB Drive
    discountValue: 50,
    targetType: 'specific_item',
  },
  {
    id: 4,
    name: 'Buy 2 Keepsakes, Get £5 Off Each',
    description: 'Add any 2 keepsake products and save £5 on each',
    active: true,
    buyQuantity: 2,
    buyItemType: 'product',
    buyCategory: 'Keepsakes',
    ruleType: 'fixed_discount',
    getQuantity: 2,
    discountValue: 5,
    targetType: 'category',
    getCategory: 'Keepsakes',
  },
  {
    id: 5,
    name: 'Inactive BXGY Rule',
    description: 'This rule is not active',
    active: false,
    buyQuantity: 1,
    buyItemType: 'any',
    ruleType: 'percentage_discount',
    getQuantity: 1,
    discountValue: 10,
    targetType: 'same_item',
  },
];

export const mockUpsellRules: UpsellRule[] = [
  {
    id: 1,
    name: 'Gender Reveal Upsell',
    description: 'Suggest Gender Reveal Package when prenatal scan is selected',
    active: true,
    priority: 10,
    conditions: [
      {
        triggerType: 'service_selected',
        serviceName: 'Prenatal Scan (20wk)',
      },
    ],
    offerType: 'addon',
    placement: ['after_service', 'pre_payment'],
    offeredItemType: 'product',
    offeredItemId: 7,
    offeredItemName: 'Gender Reveal Package',
    originalPrice: 12,
    discountedPrice: 10,
    incrementalPrice: 10,
    headline: 'Add Gender Reveal Package',
    subheadline: 'Sealed envelope with gender reveal photo - Just £10',
    badge: 'POPULAR',
    onlyShowOnce: true,
  },
  {
    id: 2,
    name: 'Digital Package Upgrade',
    description: 'Offer digital package to any scan customer',
    active: true,
    priority: 8,
    conditions: [
      {
        triggerType: 'service_selected',
      },
    ],
    offerType: 'addon',
    placement: ['after_service', 'pre_payment'],
    offeredItemType: 'product',
    offeredItemId: 2,
    offeredItemName: 'Digital Scan Package',
    originalPrice: 15,
    headline: 'Add Digital Photos Package',
    subheadline: 'All scan images delivered via email for £15',
    badge: 'RECOMMENDED',
  },
  {
    id: 3,
    name: 'Memory Bundle Upsell',
    description: 'Suggest Memory Bundle when customer adds printed photos',
    active: true,
    priority: 9,
    conditions: [
      {
        triggerType: 'product_selected',
        productId: 1, // Printed Photos
      },
    ],
    offerType: 'bundle_upsell',
    placement: ['pre_payment'],
    offeredItemType: 'bundle',
    offeredItemId: 2,
    offeredItemName: 'Memory Bundle',
    originalPrice: 55,
    discountedPrice: 45,
    incrementalPrice: 35,
    headline: 'Upgrade to Memory Bundle',
    subheadline: 'Save £10 - Get frame, extra prints, and USB drive',
    badge: 'SAVE £10',
  },
  {
    id: 4,
    name: 'Heartbeat Recording Add-on',
    description: 'Offer heartbeat recording for prenatal scans',
    active: true,
    priority: 7,
    conditions: [
      {
        triggerType: 'category_selected',
        productCategory: 'Keepsakes',
      },
    ],
    offerType: 'addon',
    placement: ['pre_payment', 'pos_checkout'],
    offeredItemType: 'product',
    offeredItemId: 5,
    offeredItemName: 'Baby Heartbeat Recording',
    originalPrice: 10,
    headline: 'Capture Baby\'s Heartbeat',
    subheadline: 'Audio recording of your baby\'s heartbeat - £10',
  },
  {
    id: 5,
    name: 'Video Recording Upsell',
    description: 'Suggest video recording for high-value bookings',
    active: true,
    priority: 6,
    conditions: [
      {
        triggerType: 'cart_value',
        minCartValue: 150,
      },
    ],
    offerType: 'addon',
    placement: ['pre_payment'],
    offeredItemType: 'product',
    offeredItemId: 6,
    offeredItemName: 'Scan Video Recording',
    originalPrice: 35,
    discountedPrice: 30,
    headline: 'Add Full Video Recording',
    subheadline: 'Complete ultrasound session video for £30 (usually £35)',
    badge: 'SAVE £5',
  },
  {
    id: 6,
    name: 'Frame Quantity Bump',
    description: 'Offer second frame at discount when one is added',
    active: true,
    priority: 5,
    conditions: [
      {
        triggerType: 'product_selected',
        productId: 3, // Premium Photo Frame
      },
    ],
    offerType: 'quantity_bump',
    placement: ['pre_payment'],
    offeredItemType: 'product',
    offeredItemId: 3,
    offeredItemName: 'Premium Photo Frame',
    originalPrice: 25,
    discountedPrice: 20,
    discountPercentage: 20,
    headline: 'Add Another Frame for 20% Off',
    subheadline: 'Second frame just £20 (save £5)',
    badge: '20% OFF',
    maxDisplaysPerSession: 1,
  },
  {
    id: 7,
    name: 'Complete Prenatal Bundle',
    description: 'Upsell complete prenatal package for prenatal customers',
    active: true,
    priority: 10,
    conditions: [
      {
        triggerType: 'service_selected',
        serviceName: 'Prenatal Scan (12wk)',
      },
    ],
    offerType: 'bundle_upsell',
    placement: ['after_service'],
    offeredItemType: 'bundle',
    offeredItemId: 1,
    offeredItemName: 'Complete Prenatal Package',
    originalPrice: 340,
    discountedPrice: 289,
    incrementalPrice: 169, // From single 12wk scan at £120
    headline: 'Upgrade to Complete Prenatal Package',
    subheadline: 'Save 15% - Includes both scans plus digital and printed keepsakes',
    badge: 'BEST VALUE',
    onlyShowOnce: true,
  },
  {
    id: 8,
    name: 'USB Drive Cross-sell',
    description: 'Suggest USB when digital package is selected',
    active: true,
    priority: 4,
    conditions: [
      {
        triggerType: 'product_selected',
        productId: 2, // Digital Scan Package
      },
    ],
    offerType: 'addon',
    placement: ['pre_payment'],
    offeredItemType: 'product',
    offeredItemId: 4,
    offeredItemName: 'USB Drive with Scans',
    originalPrice: 20,
    headline: 'Get Your Scans on USB Too',
    subheadline: '16GB USB drive with all images and videos - £20',
  },
  {
    id: 9,
    name: 'Inactive Upsell Example',
    description: 'This upsell is not active',
    active: false,
    priority: 1,
    conditions: [
      {
        triggerType: 'service_selected',
      },
    ],
    offerType: 'addon',
    placement: ['pre_payment'],
    offeredItemType: 'product',
    offeredItemId: 1,
    offeredItemName: 'Test Product',
    headline: 'Inactive Upsell',
  },
];

// Payment Plans
export const mockPaymentPlans: PaymentPlan[] = [
  {
    id: 1,
    name: 'Pay in 2 (Half Now, Half Later)',
    type: 'half_now_half_later',
    description: 'Split your payment into 2 equal installments',
    installmentCount: 2,
    minCartValue: 100,
    active: true,
  },
  {
    id: 2,
    name: '3-Month Payment Plan',
    type: 'three_pay',
    description: 'Spread your payment over 3 months',
    installmentCount: 3,
    minCartValue: 150,
    processingFeePercentage: 3,
    active: true,
  },
  {
    id: 3,
    name: '6-Month Payment Plan',
    type: 'six_pay',
    description: 'Spread your payment over 6 months with a small processing fee',
    installmentCount: 6,
    minCartValue: 300,
    processingFeePercentage: 5,
    active: true,
  },
  {
    id: 4,
    name: 'Inactive Plan Example',
    type: 'custom',
    description: 'This plan is inactive',
    installmentCount: 4,
    active: false,
  },
];

// Scaled Offers (Lite Versions)
export const mockScaledOffers: ScaledOffer[] = [
  {
    id: 1,
    name: 'Essential Prenatal Scan',
    description: 'Basic prenatal scan with essential measurements',
    originalItemType: 'service',
    originalItemId: 0,
    originalItemName: 'Prenatal Scan (20wk)',
    reducedPrice: 85,
    removedFeatures: [
      '4D imaging',
      'Gender reveal ceremony',
      'Printed photos (reduced to 2)',
      'Video recording',
    ],
    active: true,
  },
  {
    id: 2,
    name: 'Basic Print Package',
    description: 'Essential printed photos without extras',
    originalItemType: 'bundle',
    originalItemId: 1,
    originalItemName: 'Premium Print Bundle',
    reducedPrice: 20,
    removedFeatures: [
      'Photo album',
      'Canvas print',
      'Digital copies',
    ],
    active: true,
  },
  {
    id: 3,
    name: 'Standard Ultrasound',
    description: 'Standard ultrasound without premium features',
    originalItemType: 'service',
    originalItemId: 1,
    originalItemName: 'Premium Ultrasound Package',
    reducedPrice: 95,
    removedFeatures: [
      'Extended session time',
      'Multiple angle views',
      'HD video recording',
      'Same-day digital delivery',
    ],
    active: true,
  },
];

// Downsell Rules
export const mockDownsellRules: DownsellRule[] = [
  {
    id: 1,
    name: 'Payment Plan for High Cart Values',
    description: 'Offer payment plan when cart is over £150',
    active: true,
    priority: 10,
    conditions: [
      {
        triggerType: 'checkout_hesitation',
        minCartValue: 150,
      },
    ],
    offerType: 'payment_plan',
    paymentPlanId: 2, // 3-Month Payment Plan
    headline: 'Spread the cost over 3 months',
    subheadline: 'Pay in comfortable installments with no interest',
  },
  {
    id: 2,
    name: 'Essential Scan After Premium Decline',
    description: 'Offer essential scan when premium prenatal is declined',
    active: true,
    priority: 9,
    conditions: [
      {
        triggerType: 'upsell_declined',
        declinedItemType: 'service',
      },
    ],
    offerType: 'scaled_offer',
    scaledOfferId: 1, // Essential Prenatal Scan
    headline: 'Still want essential measurements?',
    subheadline: 'Get the basics at a lower price',
    onlyShowOnce: true,
  },
  {
    id: 3,
    name: 'Half Now Half Later for Medium Carts',
    description: 'Offer split payment for carts £100-£200',
    active: true,
    priority: 8,
    conditions: [
      {
        triggerType: 'checkout_hesitation',
        minCartValue: 100,
      },
    ],
    offerType: 'payment_plan',
    paymentPlanId: 1, // Half Now Half Later
    headline: 'Pay half now, half in 30 days',
    subheadline: 'Make it easier with our split payment option',
  },
  {
    id: 4,
    name: 'Basic Print Package After Bundle Decline',
    description: 'Offer basic prints when premium bundle is declined',
    active: true,
    priority: 7,
    conditions: [
      {
        triggerType: 'upsell_declined',
        declinedItemType: 'bundle',
      },
    ],
    offerType: 'scaled_offer',
    scaledOfferId: 2, // Basic Print Package
    headline: 'How about essential prints?',
    subheadline: 'Get beautiful photos without the extras',
    onlyShowOnce: true,
  },
  {
    id: 5,
    name: 'Trial Credit for Future Upgrade',
    description: 'Offer credit toward future package upgrade',
    active: true,
    priority: 6,
    conditions: [
      {
        triggerType: 'upsell_declined',
        declinedItemType: 'bundle',
      },
    ],
    offerType: 'trial_credit',
    trialCreditAmount: 20,
    trialCreditDescription: 'Book a single scan now and get £20 credit toward any package upgrade within 3 months',
    headline: 'Get £20 credit for future upgrades',
    subheadline: 'Try a single scan today, upgrade to a package later with credit applied',
  },
  {
    id: 6,
    name: '6-Month Plan for Large Purchases',
    description: 'Offer extended payment plan for carts over £300',
    active: true,
    priority: 9,
    conditions: [
      {
        triggerType: 'cart_value_threshold',
        minCartValue: 300,
      },
    ],
    offerType: 'payment_plan',
    paymentPlanId: 3, // 6-Month Payment Plan
    headline: 'Spread payments over 6 months',
    subheadline: 'Small monthly payments make it more affordable',
  },
];

export const mockUpgradeCredits: UpgradeCredit[] = [];

export const mockMembershipPlans: MembershipPlan[] = [
  {
    id: 1,
    name: 'Pregnancy Journey VIP',
    description: 'Monthly continuity plan with HD keepsakes, prenatal education, and priority booking support.',
    price: 129,
    billingInterval: 'monthly',
    minimumTermMonths: 6,
    signupFee: 49,
    cancellationFee: 79,
    includedCredits: 1,
    creditCarryoverRule: 'one_period',
    signupBonus: 1,
    perks: [
      'Priority scheduling window (7 days ahead of general release)',
      'Complimentary HD keepsake video per visit',
      'Member-only pricing on add-on products (10% off)',
    ],
    prepayDiscountPercentage: 8,
    memberPriceDiscountPercentage: 10,
    active: true,
    createdAt: new Date('2024-01-02T09:00:00Z').toISOString(),
    updatedAt: new Date('2024-08-10T15:30:00Z').toISOString(),
  },
  {
    id: 2,
    name: 'Every 4 Weeks Wellbeing',
    description: 'Consistency-focused plan billed every 4 weeks to align with trimester milestones.',
    price: 109,
    billingInterval: 'every_4_weeks',
    minimumTermMonths: 3,
    signupFee: 29,
    cancellationFee: 59,
    includedCredits: 1,
    creditCarryoverRule: 'unlimited',
    signupBonus: 0,
    perks: [
      'Dedicated sonographer concierge line',
      'Early access to seasonal bundle offers',
      'Automatic appointment reminders + rescheduling support',
    ],
    prepayDiscountPercentage: 5,
    memberPriceDiscountPercentage: 7,
    active: true,
    createdAt: new Date('2024-03-15T10:30:00Z').toISOString(),
    updatedAt: new Date('2024-12-02T12:05:00Z').toISOString(),
  },
  {
    id: 3,
    name: 'Family Keepsake Annual',
    description: 'Annual plan with quarterly HD scans, newborn session credit, and flexible carryover.',
    price: 1249,
    billingInterval: 'annually',
    minimumTermMonths: 12,
    signupFee: 0,
    cancellationFee: 149,
    includedCredits: 12,
    creditCarryoverRule: 'unlimited',
    signupBonus: 2,
    perks: [
      'Complimentary newborn photography mini-session',
      'Unlimited access to digital photo vault',
      'VIP pregnancy announcement studio time',
    ],
    prepayDiscountPercentage: 10,
    memberPriceDiscountPercentage: 15,
    active: false,
    createdAt: new Date('2023-11-20T09:15:00Z').toISOString(),
    updatedAt: new Date('2024-11-05T11:45:00Z').toISOString(),
  },
];

export const mockMemberSubscriptions: MemberSubscription[] = [
  {
    id: 101,
    memberId: 'MBR-0001',
    patientName: 'Amelia Johnson',
    planId: 1,
    planName: 'Pregnancy Journey VIP',
    status: 'active',
    price: 129,
    billingInterval: 'monthly',
    nextRenewalDate: new Date('2025-03-10T09:00:00Z').toISOString(),
    enrolledAt: new Date('2024-09-10T09:00:00Z').toISOString(),
    minimumTermMonths: 6,
    minimumTermEndDate: new Date('2025-03-10T09:00:00Z').toISOString(),
    signupFeePaid: 0,
    signupFeeWaived: true,
    prepaidUntil: undefined,
    currentPeriodCredits: 1,
    totalCreditsGranted: 8,
    totalCreditsRedeemed: 6,
    carriedOverCredits: 1,
    paymentMethods: [
      { id: 'card_visa_4242', type: 'card', last4: '4242', isPrimary: true, expiryMonth: 7, expiryYear: 2028 },
      { id: 'card_master_1881', type: 'card', last4: '1881', isPrimary: false, expiryMonth: 3, expiryYear: 2027 },
    ],
    failedPaymentCount: 0,
    lastPaymentDate: new Date('2025-02-10T09:00:00Z').toISOString(),
    lastPaymentStatus: 'success',
    notes: 'Prefers Tuesday appointments at 10am.',
    tags: ['VIP', 'High LTV'],
  },
  {
    id: 102,
    memberId: 'MBR-0007',
    patientName: 'Benjamin Carter',
    planId: 2,
    planName: 'Every 4 Weeks Wellbeing',
    status: 'past_due',
    price: 109,
    billingInterval: 'every_4_weeks',
    nextRenewalDate: new Date('2025-02-18T09:00:00Z').toISOString(),
    enrolledAt: new Date('2024-11-12T09:00:00Z').toISOString(),
    minimumTermMonths: 3,
    minimumTermEndDate: new Date('2025-02-12T09:00:00Z').toISOString(),
    signupFeePaid: 29,
    signupFeeWaived: false,
    prepaidUntil: undefined,
    currentPeriodCredits: 0,
    totalCreditsGranted: 4,
    totalCreditsRedeemed: 4,
    carriedOverCredits: 0,
    paymentMethods: [
      { id: 'card_amex_0005', type: 'card', last4: '0005', isPrimary: true, expiryMonth: 1, expiryYear: 2026 },
      { id: 'bank_gb29', type: 'bank_account', last4: '3021', isPrimary: false },
    ],
    failedPaymentCount: 1,
    lastPaymentDate: new Date('2025-01-21T09:00:00Z').toISOString(),
    lastPaymentStatus: 'failed',
    notes: 'Retry card on file before using bank mandate.',
    tags: ['Dunning'],
  },
  {
    id: 103,
    memberId: 'MBR-0014',
    patientName: 'Sophia Miller',
    planId: 3,
    planName: 'Family Keepsake Annual',
    status: 'cancelled',
    price: 1249,
    billingInterval: 'annually',
    nextRenewalDate: new Date('2025-09-01T09:00:00Z').toISOString(),
    enrolledAt: new Date('2023-09-01T09:00:00Z').toISOString(),
    cancelledAt: new Date('2024-10-15T14:30:00Z').toISOString(),
    expiresAt: new Date('2025-09-01T09:00:00Z').toISOString(),
    minimumTermMonths: 12,
    minimumTermEndDate: new Date('2024-09-01T09:00:00Z').toISOString(),
    signupFeePaid: 0,
    signupFeeWaived: true,
    prepaidUntil: new Date('2025-09-01T09:00:00Z').toISOString(),
    currentPeriodCredits: 6,
    totalCreditsGranted: 26,
    totalCreditsRedeemed: 20,
    carriedOverCredits: 4,
    paymentMethods: [
      { id: 'card_visa_7777', type: 'card', last4: '7777', isPrimary: true, expiryMonth: 11, expiryYear: 2026 },
    ],
    failedPaymentCount: 0,
    lastPaymentDate: new Date('2024-09-01T09:00:00Z').toISOString(),
    lastPaymentStatus: 'success',
    notes: 'Cancelled when moving clinic location; benefits remain until term end.',
    tags: ['Legacy'],
  },
];

export const mockMembershipEvents: MembershipEvent[] = [
  {
    id: 5001,
    subscriptionId: 101,
    memberId: 'MBR-0001',
    patientName: 'Amelia Johnson',
    eventType: 'enrolled',
    timestamp: new Date('2024-09-10T09:00:00Z').toISOString(),
    amount: 129,
    description: 'Initial charge for Pregnancy Journey VIP membership (signup fee waived with 6-month commitment).',
    paymentMethodId: 'card_visa_4242',
    paymentStatus: 'success',
    performedBy: 'system',
  },
  {
    id: 5002,
    subscriptionId: 101,
    memberId: 'MBR-0001',
    patientName: 'Amelia Johnson',
    eventType: 'bonus_granted',
    timestamp: new Date('2024-09-10T09:01:00Z').toISOString(),
    creditsChanged: 1,
    description: 'Signup bonus applied: 1 extra scan credit.',
    performedBy: 'system',
  },
  {
    id: 5003,
    subscriptionId: 101,
    memberId: 'MBR-0001',
    patientName: 'Amelia Johnson',
    eventType: 'renewed',
    timestamp: new Date('2025-02-10T09:00:00Z').toISOString(),
    amount: 129,
    creditsChanged: 1,
    description: 'Monthly renewal processed successfully. 1 scan credit added.',
    paymentMethodId: 'card_visa_4242',
    paymentStatus: 'success',
    performedBy: 'system',
  },
  {
    id: 5010,
    subscriptionId: 102,
    memberId: 'MBR-0007',
    patientName: 'Benjamin Carter',
    eventType: 'enrolled',
    timestamp: new Date('2024-11-12T09:00:00Z').toISOString(),
    amount: 138,
    description: 'Initial charge for Every 4 Weeks Wellbeing membership (includes £29 signup fee).',
    paymentMethodId: 'card_amex_0005',
    paymentStatus: 'success',
    performedBy: 'frontdesk.sarah',
  },
  {
    id: 5011,
    subscriptionId: 102,
    memberId: 'MBR-0007',
    patientName: 'Benjamin Carter',
    eventType: 'payment_failed',
    timestamp: new Date('2025-02-18T09:05:00Z').toISOString(),
    amount: 109,
    description: 'Auto-renewal failed. Card declined - insufficient funds.',
    paymentMethodId: 'card_amex_0005',
    paymentStatus: 'failed',
    failureReason: 'insufficient_funds',
    retryCount: 1,
    performedBy: 'system',
    notes: 'Retry scheduled in 3 days; will attempt secondary bank mandate if card fails again.',
  },
  {
    id: 5012,
    subscriptionId: 102,
    memberId: 'MBR-0007',
    patientName: 'Benjamin Carter',
    eventType: 'payment_retry',
    timestamp: new Date('2025-02-21T09:00:00Z').toISOString(),
    amount: 109,
    description: 'Dunning attempt scheduled using bank mandate.',
    paymentMethodId: 'bank_gb29',
    paymentStatus: 'pending',
    retryCount: 2,
    performedBy: 'system',
  },
  {
    id: 5020,
    subscriptionId: 103,
    memberId: 'MBR-0014',
    patientName: 'Sophia Miller',
    eventType: 'cancelled',
    timestamp: new Date('2024-10-15T14:30:00Z').toISOString(),
    amount: 149,
    description: 'Membership cancelled prior to renewal window. Early exit fee charged per agreement.',
    paymentMethodId: 'card_visa_7777',
    paymentStatus: 'success',
    performedBy: 'frontdesk.lucy',
    notes: 'Waived remaining credits expiration until plan term end.',
  },
];

// Referral Program Mock Data
export const mockReferralProgramConfig: import('./types').ReferralProgramConfig = {
  id: 1,
  enabled: true,
  name: 'Friend & Family Referral Program',
  description: 'Share your love for SonoRecall! Give £10 off to friends, get £15 credit when they book.',
  // Referee incentive
  refereeIncentiveType: 'fixed_discount',
  refereeIncentiveValue: 10, // £10 off
  refereeMinimumPurchase: 50, // must spend at least £50
  // Referrer reward
  referrerRewardType: 'account_credit',
  referrerRewardValue: 15, // £15 credit
  // Limits
  maxUsesPerReferee: 1, // one-time use per new customer
  maxRewardsPerReferrer: undefined, // unlimited
  requireCompletedPurchase: true,
  preventSelfReferral: true,
  expiryDays: 90, // codes expire after 90 days
  // Fraud prevention
  minDaysBetweenReferrals: 1, // prevent rapid referrals
  requireUniqueEmail: true,
  requireUniquePhone: true,
  createdAt: new Date('2024-06-01T10:00:00Z').toISOString(),
  updatedAt: new Date('2025-01-15T09:00:00Z').toISOString(),
};

export const mockCustomerReferralCodes: import('./types').CustomerReferralCode[] = [
  {
    id: 1,
    customerName: 'Sarah Thompson',
    customerEmail: 'sarah.thompson@email.com',
    customerPhone: '+447700900001',
    referralCode: 'SARAH25',
    createdAt: new Date('2024-08-01T10:00:00Z').toISOString(),
    expiresAt: new Date('2025-10-30T23:59:59Z').toISOString(),
    active: true,
    totalReferrals: 3,
    totalRewardsEarned: 45, // 3 * £15
  },
  {
    id: 2,
    customerName: 'Emma Wilson',
    customerEmail: 'emma.wilson@email.com',
    customerPhone: '+447700900002',
    referralCode: 'EMMA2025',
    createdAt: new Date('2024-09-15T14:30:00Z').toISOString(),
    expiresAt: new Date('2025-12-15T23:59:59Z').toISOString(),
    active: true,
    totalReferrals: 5,
    totalRewardsEarned: 75,
  },
  {
    id: 3,
    customerName: 'Olivia Brown',
    customerEmail: 'olivia.brown@email.com',
    customerPhone: '+447700900003',
    referralCode: 'OLIVIA10',
    createdAt: new Date('2024-07-20T09:00:00Z').toISOString(),
    active: true,
    totalReferrals: 1,
    totalRewardsEarned: 15,
  },
  {
    id: 4,
    customerName: 'Charlotte Evans',
    customerEmail: 'charlotte.evans@email.com',
    customerPhone: '+447700900004',
    referralCode: 'CHAR2024',
    createdAt: new Date('2024-10-05T16:20:00Z').toISOString(),
    active: true,
    totalReferrals: 0,
    totalRewardsEarned: 0,
  },
];

export const mockReferralRelationships: import('./types').ReferralRelationship[] = [
  {
    id: 1,
    referrerCode: 'SARAH25',
    referrerName: 'Sarah Thompson',
    refereeName: 'Jessica Martinez',
    refereeEmail: 'jessica.m@email.com',
    refereePhone: '+447700900101',
    referredAt: new Date('2024-09-10T11:30:00Z').toISOString(),
    status: 'rewarded',
    refereeIncentiveApplied: {
      type: 'fixed_discount',
      value: 10,
    },
    referrerRewardIssued: {
      type: 'account_credit',
      value: 15,
      creditId: 201,
    },
    appointmentId: 2001,
    purchaseAmount: 120,
    completedAt: new Date('2024-09-10T14:00:00Z').toISOString(),
    rewardedAt: new Date('2024-09-10T14:05:00Z').toISOString(),
    fraudChecksPassed: true,
  },
  {
    id: 2,
    referrerCode: 'EMMA2025',
    referrerName: 'Emma Wilson',
    refereeName: 'Rachel Adams',
    refereeEmail: 'rachel.adams@email.com',
    refereePhone: '+447700900102',
    referredAt: new Date('2024-10-15T09:45:00Z').toISOString(),
    status: 'rewarded',
    refereeIncentiveApplied: {
      type: 'fixed_discount',
      value: 10,
    },
    referrerRewardIssued: {
      type: 'account_credit',
      value: 15,
      creditId: 202,
    },
    appointmentId: 2002,
    purchaseAmount: 95,
    completedAt: new Date('2024-10-15T13:30:00Z').toISOString(),
    rewardedAt: new Date('2024-10-15T13:35:00Z').toISOString(),
    fraudChecksPassed: true,
  },
  {
    id: 3,
    referrerCode: 'SARAH25',
    referrerName: 'Sarah Thompson',
    refereeName: 'Amanda Clark',
    refereeEmail: 'amanda.clark@email.com',
    refereePhone: '+447700900103',
    referredAt: new Date('2024-11-20T16:10:00Z').toISOString(),
    status: 'completed',
    refereeIncentiveApplied: {
      type: 'fixed_discount',
      value: 10,
    },
    appointmentId: 2003,
    purchaseAmount: 85,
    completedAt: new Date('2024-11-20T17:00:00Z').toISOString(),
    fraudChecksPassed: true,
  },
  {
    id: 4,
    referrerCode: 'OLIVIA10',
    referrerName: 'Olivia Brown',
    refereeName: 'Lauren Phillips',
    refereeEmail: 'lauren.p@email.com',
    refereePhone: '+447700900104',
    referredAt: new Date('2025-01-05T10:20:00Z').toISOString(),
    status: 'pending',
    refereeIncentiveApplied: {
      type: 'fixed_discount',
      value: 10,
    },
    fraudChecksPassed: true,
  },
];

export const mockReferralEvents: import('./types').ReferralEvent[] = [
  {
    id: 1,
    relationshipId: 1,
    type: 'code_applied',
    timestamp: new Date('2024-09-10T11:30:00Z').toISOString(),
    data: { code: 'SARAH25', discount: 10 },
  },
  {
    id: 2,
    relationshipId: 1,
    type: 'purchase_completed',
    timestamp: new Date('2024-09-10T14:00:00Z').toISOString(),
    data: { appointmentId: 2001, amount: 120 },
  },
  {
    id: 3,
    relationshipId: 1,
    type: 'referee_rewarded',
    timestamp: new Date('2024-09-10T14:05:00Z').toISOString(),
    data: { discount: 10 },
  },
  {
    id: 4,
    relationshipId: 1,
    type: 'referrer_rewarded',
    timestamp: new Date('2024-09-10T14:05:00Z').toISOString(),
    data: { creditId: 201, amount: 15 },
  },
  {
    id: 5,
    relationshipId: 2,
    type: 'code_applied',
    timestamp: new Date('2024-10-15T09:45:00Z').toISOString(),
    data: { code: 'EMMA2025', discount: 10 },
  },
  {
    id: 6,
    relationshipId: 2,
    type: 'purchase_completed',
    timestamp: new Date('2024-10-15T13:30:00Z').toISOString(),
    data: { appointmentId: 2002, amount: 95 },
  },
];

// CRM Automation Mock Data
export const mockCampaignTriggers: CampaignTriggerConfig[] = [
  {
    id: 1,
    name: 'Cart Abandonment Recovery',
    description: 'Send reminder when customer abandons booking with cart over £50',
    triggerType: 'booking_abandonment',
    enabled: true,
    channel: 'email',
    priority: 10,
    sendWindowStart: '09:00',
    sendWindowEnd: '20:00',
    respectQuietHours: true,
    quietHoursStart: '21:00',
    quietHoursEnd: '08:00',
    conditions: {
      minCartValue: 50,
      abandonedForMinutes: 60,
    },
    emailTemplate: `<html>
<body>
  <h2>Hi {{patientName}},</h2>
  <p>We noticed you didn't complete your booking for <strong>{{serviceName}}</strong>.</p>
  <p>Your appointment slot is still available! Complete your booking now before it's gone.</p>
  <p><strong>Cart Total: £{{cartTotal}}</strong></p>
  <a href="{{bookingUrl}}" style="background: #4CAF50; color: white; padding: 12px 24px; text-decoration: none; border-radius: 4px;">Complete Booking</a>
  <p style="margin-top: 20px;">Need help? Reply to this email or call us at 020 1234 5678.</p>
  <p style="color: #666; font-size: 12px;">SonoRecall Clinic | Your trusted sonography partner</p>
</body>
</html>`,
    smsTemplate: 'Hi {{patientName}}, your booking for {{serviceName}} (£{{cartTotal}}) is waiting! Complete it here: {{bookingUrl}}',
    delayMinutes: 60,
    maxMessagesPerWeek: 2,
    maxMessagesPerCampaign: 1,
    retryFailedSends: true,
    maxRetries: 3,
    suppressionRules: ['unsubscribed_all', 'opted_out_campaign'],
    trackOpens: true,
    trackClicks: true,
    createdAt: new Date('2024-05-01T10:00:00Z').toISOString(),
    updatedAt: new Date('2025-01-15T14:30:00Z').toISOString(),
  },
  {
    id: 2,
    name: '12-Week Pregnancy Scan Reminder',
    description: 'Lifecycle campaign for 12-week prenatal scan booking',
    triggerType: 'lifecycle_pregnancy',
    enabled: true,
    channel: 'email',
    priority: 9,
    sendWindowStart: '10:00',
    sendWindowEnd: '18:00',
    respectQuietHours: true,
    quietHoursStart: '20:00',
    quietHoursEnd: '09:00',
    conditions: {
      pregnancyWeeks: [11, 12],
    },
    emailTemplate: `<html>
<body>
  <h2>Congratulations on your pregnancy, {{patientName}}! 🎉</h2>
  <p>You're approaching 12 weeks - the perfect time for your first prenatal scan.</p>
  <h3>What to expect at your 12-week scan:</h3>
  <ul>
    <li>Confirm your due date</li>
    <li>Check baby's development</li>
    <li>See your baby for the first time!</li>
    <li>Receive beautiful keepsake photos</li>
  </ul>
  <p><strong>Special offer: Book now and get 10% off your scan package.</strong></p>
  <a href="{{bookingUrl}}" style="background: #FF6B9D; color: white; padding: 12px 24px; text-decoration: none; border-radius: 4px;">Book Your 12-Week Scan</a>
  <p style="margin-top: 20px;">Questions? We're here to help: 020 1234 5678</p>
</body>
</html>`,
    smsTemplate: 'Hi {{patientName}}, you\'re at 12 weeks! Time to book your first prenatal scan. Book now with 10% off: {{bookingUrl}}',
    delayMinutes: 0,
    maxMessagesPerWeek: 1,
    maxMessagesPerCampaign: 2,
    retryFailedSends: true,
    maxRetries: 2,
    suppressionRules: ['unsubscribed_marketing'],
    trackOpens: true,
    trackClicks: true,
    createdAt: new Date('2024-06-15T09:00:00Z').toISOString(),
    updatedAt: new Date('2024-12-10T11:20:00Z').toISOString(),
  },
  {
    id: 3,
    name: '20-Week Anatomy Scan Reminder',
    description: 'Lifecycle campaign for 20-week detailed scan',
    triggerType: 'lifecycle_pregnancy',
    enabled: true,
    channel: 'email',
    priority: 9,
    sendWindowStart: '10:00',
    sendWindowEnd: '18:00',
    respectQuietHours: true,
    quietHoursStart: '20:00',
    quietHoursEnd: '09:00',
    conditions: {
      pregnancyWeeks: [19, 20],
    },
    emailTemplate: `<html>
<body>
  <h2>Your 20-Week Anatomy Scan Awaits, {{patientName}}! 👶</h2>
  <p>This is one of the most exciting scans - you'll see your baby in detail and may learn the gender!</p>
  <h3>What's included:</h3>
  <ul>
    <li>Detailed anatomy check</li>
    <li>Optional gender reveal</li>
    <li>4D imaging available</li>
    <li>HD video recording</li>
    <li>Premium photo package</li>
  </ul>
  <p><strong>Upgrade to our Complete Prenatal Package and save 15%!</strong></p>
  <a href="{{bookingUrl}}" style="background: #4CAF50; color: white; padding: 12px 24px; text-decoration: none; border-radius: 4px;">Book Your 20-Week Scan</a>
</body>
</html>`,
    delayMinutes: 0,
    maxMessagesPerWeek: 1,
    maxMessagesPerCampaign: 2,
    retryFailedSends: true,
    maxRetries: 2,
    suppressionRules: ['unsubscribed_marketing'],
    trackOpens: true,
    trackClicks: true,
    createdAt: new Date('2024-06-15T09:00:00Z').toISOString(),
    updatedAt: new Date('2024-12-10T11:20:00Z').toISOString(),
  },
  {
    id: 4,
    name: '6-Week Follow-up Reminder',
    description: 'Remind customers to book follow-up scan 6 weeks after last visit',
    triggerType: 'lifecycle_time_since_scan',
    enabled: true,
    channel: 'sms',
    priority: 7,
    sendWindowStart: '10:00',
    sendWindowEnd: '17:00',
    respectQuietHours: true,
    quietHoursStart: '20:00',
    quietHoursEnd: '09:00',
    conditions: {
      daysSinceLastVisit: 42,
    },
    emailTemplate: `<html>
<body>
  <h2>Time for Your Follow-Up, {{patientName}}</h2>
  <p>It's been 6 weeks since your last scan on {{lastVisitDate}}.</p>
  <p>Book your follow-up scan to ensure everything is progressing well.</p>
  <a href="{{bookingUrl}}" style="background: #2196F3; color: white; padding: 12px 24px; text-decoration: none; border-radius: 4px;">Book Follow-Up Scan</a>
</body>
</html>`,
    smsTemplate: 'Hi {{patientName}}, it\'s been 6 weeks since your scan. Time to book your follow-up! {{bookingUrl}}',
    delayMinutes: 0,
    maxMessagesPerWeek: 1,
    maxMessagesPerCampaign: 1,
    retryFailedSends: false,
    maxRetries: 0,
    suppressionRules: ['unsubscribed_all'],
    trackOpens: false,
    trackClicks: true,
    createdAt: new Date('2024-07-01T10:00:00Z').toISOString(),
    updatedAt: new Date('2024-11-20T09:15:00Z').toISOString(),
  },
  {
    id: 5,
    name: 'Membership Renewal Reminder',
    description: 'Remind members 7 days before renewal',
    triggerType: 'membership_renewal',
    enabled: true,
    channel: 'email',
    priority: 8,
    sendWindowStart: '09:00',
    sendWindowEnd: '19:00',
    respectQuietHours: true,
    quietHoursStart: '21:00',
    quietHoursEnd: '08:00',
    conditions: {
      daysBeforeRenewal: 7,
    },
    emailTemplate: `<html>
<body>
  <h2>Your Membership Renews Soon, {{patientName}}</h2>
  <p>Your {{membershipPlan}} membership will renew on {{renewalDate}} for £{{renewalAmount}}.</p>
  <h3>Your Benefits:</h3>
  <ul>
    <li>{{includedCredits}} scan credits per {{billingInterval}}</li>
    <li>Priority booking access</li>
    <li>Member-exclusive pricing</li>
    <li>{{perks}}</li>
  </ul>
  <p>Current credit balance: <strong>{{availableCredits}} credits</strong></p>
  <p>Payment method: Card ending in {{cardLast4}}</p>
  <a href="{{accountUrl}}" style="background: #9C27B0; color: white; padding: 12px 24px; text-decoration: none; border-radius: 4px;">Manage Membership</a>
  <p style="margin-top: 20px; font-size: 12px; color: #666;">Need to update payment info? Visit your account or call 020 1234 5678.</p>
</body>
</html>`,
    delayMinutes: 0,
    maxMessagesPerWeek: 1,
    maxMessagesPerCampaign: 1,
    retryFailedSends: false,
    maxRetries: 0,
    suppressionRules: [],
    trackOpens: true,
    trackClicks: true,
    createdAt: new Date('2024-08-01T10:00:00Z').toISOString(),
    updatedAt: new Date('2025-01-05T14:00:00Z').toISOString(),
  },
  {
    id: 6,
    name: 'Reactivation Campaign - 90 Days Lapsed',
    description: 'Win back customers who haven\'t visited in 90+ days',
    triggerType: 'reactivation',
    enabled: true,
    channel: 'email',
    priority: 6,
    sendWindowStart: '10:00',
    sendWindowEnd: '18:00',
    respectQuietHours: true,
    quietHoursStart: '20:00',
    quietHoursEnd: '09:00',
    conditions: {
      daysSinceLastVisit: 90,
      minDaysSinceLastVisit: 90,
      maxDaysSinceLastVisit: 180,
    },
    emailTemplate: `<html>
<body>
  <h2>We Miss You, {{patientName}}! 💙</h2>
  <p>It's been a while since we've seen you at SonoRecall Clinic.</p>
  <p>We'd love to welcome you back with a <strong>special 20% off</strong> your next scan or package.</p>
  <h3>Popular Services:</h3>
  <ul>
    <li>Prenatal Scans - From £120</li>
    <li>Abdominal Ultrasound - £150</li>
    <li>Complete Prenatal Package - Save 15%</li>
  </ul>
  <p><strong>Use code WELCOME20 at checkout for 20% off.</strong></p>
  <a href="{{bookingUrl}}" style="background: #FF5722; color: white; padding: 12px 24px; text-decoration: none; border-radius: 4px;">Book Now & Save</a>
  <p style="margin-top: 20px; font-size: 12px;">Offer valid for 14 days. Not applicable with other discounts.</p>
</body>
</html>`,
    smsTemplate: 'We miss you {{patientName}}! Get 20% off your next scan with code WELCOME20. Book now: {{bookingUrl}}',
    delayMinutes: 0,
    maxMessagesPerWeek: 1,
    maxMessagesPerCampaign: 2,
    retryFailedSends: false,
    maxRetries: 0,
    suppressionRules: ['unsubscribed_marketing', 'opted_out_campaign'],
    trackOpens: true,
    trackClicks: true,
    createdAt: new Date('2024-09-01T10:00:00Z').toISOString(),
    updatedAt: new Date('2024-12-15T16:45:00Z').toISOString(),
  },
  {
    id: 7,
    name: 'Post-Visit Upsell - Digital Package',
    description: 'Offer digital scan package 24 hours after appointment',
    triggerType: 'post_visit_upsell',
    enabled: true,
    channel: 'email',
    priority: 5,
    sendWindowStart: '11:00',
    sendWindowEnd: '19:00',
    respectQuietHours: true,
    quietHoursStart: '21:00',
    quietHoursEnd: '09:00',
    conditions: {
      hoursAfterVisit: 24,
      minPurchaseAmount: 80,
    },
    emailTemplate: `<html>
<body>
  <h2>Treasure Your Memories Forever, {{patientName}}</h2>
  <p>Thank you for visiting us yesterday! We hope you loved your scan experience.</p>
  <p>Want to keep those precious images forever? <strong>Add our Digital Scan Package</strong> for just £15:</p>
  <ul>
    <li>High-resolution digital images</li>
    <li>Delivered via secure email link</li>
    <li>Download and share unlimited times</li>
    <li>Perfect for sharing with family</li>
  </ul>
  <p><strong>Special post-visit price: £12 (save £3!)</strong></p>
  <a href="{{upsellUrl}}" style="background: #00BCD4; color: white; padding: 12px 24px; text-decoration: none; border-radius: 4px;">Add Digital Package</a>
  <p style="margin-top: 20px;">Also available: USB drives (£20), premium frames (£25), video recordings (£35)</p>
</body>
</html>`,
    delayMinutes: 1440,
    maxMessagesPerWeek: 3,
    maxMessagesPerCampaign: 1,
    retryFailedSends: false,
    maxRetries: 0,
    suppressionRules: ['unsubscribed_marketing'],
    trackOpens: true,
    trackClicks: true,
    createdAt: new Date('2024-10-01T10:00:00Z').toISOString(),
    updatedAt: new Date('2025-01-10T13:20:00Z').toISOString(),
  },
  {
    id: 8,
    name: 'SMS Cart Abandonment - High Value',
    description: 'SMS follow-up for abandoned carts over £150',
    triggerType: 'booking_abandonment',
    enabled: true,
    channel: 'sms',
    priority: 9,
    sendWindowStart: '10:00',
    sendWindowEnd: '19:00',
    respectQuietHours: true,
    quietHoursStart: '20:00',
    quietHoursEnd: '09:00',
    conditions: {
      minCartValue: 150,
      abandonedForMinutes: 180,
    },
    smsTemplate: 'Hi {{patientName}}, your £{{cartTotal}} booking for {{serviceName}} is still available! Complete it in 1 click: {{bookingUrl}}. Reply STOP to opt out.',
    delayMinutes: 180,
    maxMessagesPerWeek: 1,
    maxMessagesPerCampaign: 1,
    retryFailedSends: false,
    maxRetries: 0,
    suppressionRules: ['unsubscribed_all', 'opted_out_sms'],
    trackOpens: false,
    trackClicks: true,
    createdAt: new Date('2024-11-01T10:00:00Z').toISOString(),
    updatedAt: new Date('2025-01-20T15:10:00Z').toISOString(),
  },
];

export const mockCampaignMessages: CampaignMessage[] = [
  {
    id: 1,
    campaignTriggerId: 1,
    campaignName: 'Cart Abandonment Recovery',
    patientName: 'Emma Wilson',
    patientEmail: 'emma.wilson@email.com',
    patientPhone: '+447700900002',
    channel: 'email',
    subject: 'Your booking is waiting!',
    content: '<html><body><h2>Hi Emma Wilson,</h2><p>We noticed you didn\'t complete your booking for <strong>Prenatal Scan (20wk)</strong>.</p></body></html>',
    status: 'delivered',
    queuedAt: new Date('2025-01-15T14:30:00Z').toISOString(),
    sentAt: new Date('2025-01-15T14:32:00Z').toISOString(),
    deliveredAt: new Date('2025-01-15T14:32:15Z').toISOString(),
    opened: true,
    openedAt: new Date('2025-01-15T16:20:00Z').toISOString(),
    clicked: true,
    clickedAt: new Date('2025-01-15T16:21:00Z').toISOString(),
    converted: true,
    convertedAt: new Date('2025-01-15T16:25:00Z').toISOString(),
    conversionValue: 220,
    conversionType: 'booking_completed',
    mergeData: {
      patientName: 'Emma Wilson',
      serviceName: 'Prenatal Scan (20wk)',
      cartTotal: '220',
      bookingUrl: 'https://sonorecall.com/book/resume/abc123',
    },
  },
  {
    id: 2,
    campaignTriggerId: 2,
    campaignName: '12-Week Pregnancy Scan Reminder',
    patientName: 'Jessica Martinez',
    patientEmail: 'jessica.m@email.com',
    patientPhone: '+447700900101',
    channel: 'email',
    subject: 'Time for your 12-week scan! 🎉',
    content: '<html><body><h2>Congratulations on your pregnancy, Jessica Martinez! 🎉</h2></body></html>',
    status: 'delivered',
    queuedAt: new Date('2025-01-20T10:00:00Z').toISOString(),
    sentAt: new Date('2025-01-20T10:02:00Z').toISOString(),
    deliveredAt: new Date('2025-01-20T10:02:10Z').toISOString(),
    opened: true,
    openedAt: new Date('2025-01-20T14:30:00Z').toISOString(),
    clicked: false,
    converted: false,
    mergeData: {
      patientName: 'Jessica Martinez',
      pregnancyWeek: '12',
      bookingUrl: 'https://sonorecall.com/book/prenatal-12wk',
    },
  },
  {
    id: 3,
    campaignTriggerId: 4,
    campaignName: '6-Week Follow-up Reminder',
    patientName: 'Rachel Adams',
    patientEmail: 'rachel.adams@email.com',
    patientPhone: '+447700900102',
    channel: 'sms',
    content: 'Hi Rachel Adams, it\'s been 6 weeks since your scan. Time to book your follow-up! https://sonorecall.com/book',
    status: 'delivered',
    queuedAt: new Date('2025-01-18T10:00:00Z').toISOString(),
    sentAt: new Date('2025-01-18T10:01:00Z').toISOString(),
    deliveredAt: new Date('2025-01-18T10:01:05Z').toISOString(),
    opened: false,
    clicked: true,
    clickedAt: new Date('2025-01-18T15:45:00Z').toISOString(),
    converted: true,
    convertedAt: new Date('2025-01-18T15:50:00Z').toISOString(),
    conversionValue: 90,
    conversionType: 'booking_completed',
    mergeData: {
      patientName: 'Rachel Adams',
      lastVisitDate: '2024-12-07',
      bookingUrl: 'https://sonorecall.com/book',
    },
  },
  {
    id: 4,
    campaignTriggerId: 5,
    campaignName: 'Membership Renewal Reminder',
    patientName: 'Amelia Johnson',
    patientEmail: 'amelia.j@example.com',
    patientPhone: '+447700900001',
    channel: 'email',
    subject: 'Your membership renews in 7 days',
    content: '<html><body><h2>Your Membership Renews Soon, Amelia Johnson</h2></body></html>',
    status: 'delivered',
    queuedAt: new Date('2025-01-22T09:00:00Z').toISOString(),
    sentAt: new Date('2025-01-22T09:02:00Z').toISOString(),
    deliveredAt: new Date('2025-01-22T09:02:08Z').toISOString(),
    opened: true,
    openedAt: new Date('2025-01-22T11:15:00Z').toISOString(),
    clicked: false,
    converted: false,
    mergeData: {
      patientName: 'Amelia Johnson',
      membershipPlan: 'Pregnancy Journey VIP',
      renewalDate: '2025-01-29',
      renewalAmount: '129',
      includedCredits: '1',
      billingInterval: 'month',
      availableCredits: '2',
      cardLast4: '4242',
      accountUrl: 'https://sonorecall.com/account',
    },
  },
  {
    id: 5,
    campaignTriggerId: 6,
    campaignName: 'Reactivation Campaign - 90 Days Lapsed',
    patientName: 'Chloe Davies',
    patientEmail: 'chloe.d@example.com',
    patientPhone: '+447700900003',
    channel: 'email',
    subject: 'We miss you! 20% off your next visit',
    content: '<html><body><h2>We Miss You, Chloe Davies! 💙</h2></body></html>',
    status: 'delivered',
    queuedAt: new Date('2025-01-19T10:00:00Z').toISOString(),
    sentAt: new Date('2025-01-19T10:02:00Z').toISOString(),
    deliveredAt: new Date('2025-01-19T10:02:12Z').toISOString(),
    opened: false,
    clicked: false,
    converted: false,
    mergeData: {
      patientName: 'Chloe Davies',
      lastVisitDate: '2024-10-15',
      bookingUrl: 'https://sonorecall.com/book?promo=WELCOME20',
    },
  },
  {
    id: 6,
    campaignTriggerId: 7,
    campaignName: 'Post-Visit Upsell - Digital Package',
    patientName: 'Lauren Phillips',
    patientEmail: 'lauren.p@email.com',
    patientPhone: '+447700900104',
    channel: 'email',
    subject: 'Add digital photos to your scan package',
    content: '<html><body><h2>Treasure Your Memories Forever, Lauren Phillips</h2></body></html>',
    status: 'delivered',
    queuedAt: new Date('2025-01-21T11:00:00Z').toISOString(),
    sentAt: new Date('2025-01-21T11:02:00Z').toISOString(),
    deliveredAt: new Date('2025-01-21T11:02:09Z').toISOString(),
    opened: true,
    openedAt: new Date('2025-01-21T18:30:00Z').toISOString(),
    clicked: true,
    clickedAt: new Date('2025-01-21T18:31:00Z').toISOString(),
    converted: true,
    convertedAt: new Date('2025-01-21T18:35:00Z').toISOString(),
    conversionValue: 12,
    conversionType: 'product_purchased',
    mergeData: {
      patientName: 'Lauren Phillips',
      appointmentDate: '2025-01-20',
      upsellUrl: 'https://sonorecall.com/upsell/digital-package',
    },
  },
  {
    id: 7,
    campaignTriggerId: 1,
    campaignName: 'Cart Abandonment Recovery',
    patientName: 'Daniel Smith',
    patientEmail: 'dan.smith@example.com',
    patientPhone: '+447700900004',
    channel: 'email',
    subject: 'Your booking is waiting!',
    content: '<html><body><h2>Hi Daniel Smith,</h2></body></html>',
    status: 'failed',
    queuedAt: new Date('2025-01-23T14:00:00Z').toISOString(),
    sentAt: new Date('2025-01-23T14:02:00Z').toISOString(),
    failedAt: new Date('2025-01-23T14:02:05Z').toISOString(),
    failureReason: 'invalid_email',
    retryCount: 0,
    mergeData: {
      patientName: 'Daniel Smith',
      serviceName: 'Abdominal Ultrasound',
      cartTotal: '150',
      bookingUrl: 'https://sonorecall.com/book/resume/def456',
    },
  },
  {
    id: 8,
    campaignTriggerId: 8,
    campaignName: 'SMS Cart Abandonment - High Value',
    patientName: 'Isla Taylor',
    patientEmail: 'isla.taylor@example.com',
    patientPhone: '+447700900003',
    channel: 'sms',
    content: 'Hi Isla Taylor, your £180 booking for Musculoskeletal Scan is still available! Complete it in 1 click: https://sonorecall.com/book/xyz',
    status: 'queued',
    queuedAt: new Date('2025-01-24T12:00:00Z').toISOString(),
    scheduledFor: new Date('2025-01-24T15:00:00Z').toISOString(),
    mergeData: {
      patientName: 'Isla Taylor',
      serviceName: 'Musculoskeletal Scan',
      cartTotal: '180',
      bookingUrl: 'https://sonorecall.com/book/xyz',
    },
  },
];

export const mockCustomerPreferences: CustomerCommunicationPreferences[] = [
  {
    id: 1,
    patientName: 'Amelia Johnson',
    patientEmail: 'amelia.j@example.com',
    patientPhone: '+447700900001',
    emailConsent: true,
    smsConsent: true,
    marketingConsent: true,
    unsubscribedFromAll: false,
    preferredChannel: 'email',
    optOutCampaigns: [],
    quietHoursEnabled: true,
    quietHoursStart: '21:00',
    quietHoursEnd: '08:00',
    maxMessagesPerWeek: 5,
    createdAt: new Date('2024-01-15T10:00:00Z').toISOString(),
    updatedAt: new Date('2024-09-10T14:30:00Z').toISOString(),
  },
  {
    id: 2,
    patientName: 'Benjamin Carter',
    patientEmail: 'b.carter@example.com',
    patientPhone: '+447700900002',
    emailConsent: true,
    smsConsent: false,
    marketingConsent: true,
    unsubscribedFromAll: false,
    preferredChannel: 'email',
    optOutCampaigns: [8],
    quietHoursEnabled: false,
    maxMessagesPerWeek: 3,
    createdAt: new Date('2024-04-20T09:00:00Z').toISOString(),
    updatedAt: new Date('2025-01-10T11:15:00Z').toISOString(),
  },
  {
    id: 3,
    patientName: 'Chloe Davies',
    patientEmail: 'chloe.d@example.com',
    patientPhone: '+447700900003',
    emailConsent: true,
    smsConsent: true,
    marketingConsent: false,
    unsubscribedFromAll: false,
    preferredChannel: 'email',
    optOutCampaigns: [6, 7],
    quietHoursEnabled: true,
    quietHoursStart: '20:00',
    quietHoursEnd: '09:00',
    maxMessagesPerWeek: 2,
    createdAt: new Date('2024-01-10T10:00:00Z').toISOString(),
    updatedAt: new Date('2024-11-05T16:45:00Z').toISOString(),
  },
  {
    id: 4,
    patientName: 'Daniel Smith',
    patientEmail: 'dan.smith@example.com',
    patientPhone: '+447700900004',
    emailConsent: false,
    smsConsent: false,
    marketingConsent: false,
    unsubscribedFromAll: true,
    unsubscribedAt: new Date('2024-12-01T14:20:00Z').toISOString(),
    preferredChannel: 'email',
    optOutCampaigns: [],
    quietHoursEnabled: false,
    createdAt: new Date('2024-06-01T10:00:00Z').toISOString(),
    updatedAt: new Date('2024-12-01T14:20:00Z').toISOString(),
  },
  {
    id: 5,
    patientName: 'Emma Wilson',
    patientEmail: 'emma.wilson@email.com',
    patientPhone: '+447700900002',
    emailConsent: true,
    smsConsent: true,
    marketingConsent: true,
    unsubscribedFromAll: false,
    preferredChannel: 'sms',
    optOutCampaigns: [],
    quietHoursEnabled: true,
    quietHoursStart: '22:00',
    quietHoursEnd: '07:00',
    maxMessagesPerWeek: 7,
    createdAt: new Date('2024-09-15T14:30:00Z').toISOString(),
    updatedAt: new Date('2025-01-15T10:00:00Z').toISOString(),
  },
];

export const mockCampaignQueue: CampaignQueueItem[] = [
  {
    id: 1,
    campaignTriggerId: 1,
    patientName: 'George Brown',
    patientEmail: 'george.brown@email.com',
    patientPhone: '+447700900007',
    channel: 'email',
    scheduledFor: new Date('2025-01-25T14:00:00Z').toISOString(),
    priority: 10,
    status: 'pending',
    attempts: 0,
    mergeData: {
      patientName: 'George Brown',
      serviceName: 'Abdominal Ultrasound',
      cartTotal: '150',
      bookingUrl: 'https://sonorecall.com/book/resume/ghi789',
    },
    createdAt: new Date('2025-01-25T13:00:00Z').toISOString(),
  },
  {
    id: 2,
    campaignTriggerId: 3,
    patientName: 'Sophia Miller',
    patientEmail: 'sophia.m@example.com',
    patientPhone: '+447700900005',
    channel: 'email',
    scheduledFor: new Date('2025-01-26T10:00:00Z').toISOString(),
    priority: 9,
    status: 'pending',
    attempts: 0,
    mergeData: {
      patientName: 'Sophia Miller',
      pregnancyWeek: '20',
      bookingUrl: 'https://sonorecall.com/book/prenatal-20wk',
    },
    createdAt: new Date('2025-01-25T16:00:00Z').toISOString(),
  },
  {
    id: 3,
    campaignTriggerId: 4,
    patientName: 'Jacob Moore',
    patientEmail: 'jacob.m@example.com',
    patientPhone: '+447700900006',
    channel: 'sms',
    scheduledFor: new Date('2025-01-25T11:00:00Z').toISOString(),
    priority: 7,
    status: 'sending',
    attempts: 1,
    mergeData: {
      patientName: 'Jacob Moore',
      lastVisitDate: '2024-12-14',
      bookingUrl: 'https://sonorecall.com/book',
    },
    createdAt: new Date('2025-01-25T10:30:00Z').toISOString(),
  },
];

export const mockCampaignMetrics: CampaignMetrics = {
  totalMessagesSent: 2847,
  totalMessagesDelivered: 2756,
  totalOpens: 1524,
  totalClicks: 892,
  totalConversions: 247,
  totalRevenue: 42580,
  openRate: 55.3,
  clickRate: 32.4,
  conversionRate: 8.7,
  revenuePerMessage: 14.96,
  averageOrderValue: 172.42,
  totalCost: 8541,
  roi: 398.5,
  campaignBreakdown: [
    {
      campaignId: 1,
      campaignName: 'Cart Abandonment Recovery',
      messagesSent: 523,
      messagesDelivered: 512,
      opens: 289,
      clicks: 167,
      conversions: 78,
      revenue: 14650,
      openRate: 56.4,
      clickRate: 32.6,
      conversionRate: 15.2,
    },
    {
      campaignId: 2,
      campaignName: '12-Week Pregnancy Scan Reminder',
      messagesSent: 412,
      messagesDelivered: 398,
      opens: 245,
      clicks: 178,
      conversions: 52,
      revenue: 6240,
      openRate: 61.6,
      clickRate: 44.7,
      conversionRate: 13.1,
    },
    {
      campaignId: 6,
      campaignName: 'Reactivation Campaign - 90 Days Lapsed',
      messagesSent: 789,
      messagesDelivered: 765,
      opens: 412,
      clicks: 234,
      conversions: 67,
      revenue: 11890,
      openRate: 53.9,
      clickRate: 30.6,
      conversionRate: 8.8,
    },
    {
      campaignId: 7,
      campaignName: 'Post-Visit Upsell - Digital Package',
      messagesSent: 1123,
      messagesDelivered: 1081,
      opens: 578,
      clicks: 313,
      conversions: 50,
      revenue: 9800,
      openRate: 53.5,
      clickRate: 28.9,
      conversionRate: 4.6,
    },
  ],
  periodStart: new Date('2024-07-01T00:00:00Z').toISOString(),
  periodEnd: new Date('2025-01-24T23:59:59Z').toISOString(),
};
